version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test:unit:once
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo ${CODEBUILD_SOURCE_VERSION} > .version
artifacts:
  files:
    - app/**/*
    - tmp/backend.yaml
    - .version
