version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test:unit:once
  build:
    commands:
      - npm run package:app -- --s3-bucket ${ARTIFACTS_BUCKET} --s3-prefix lambda
      - npm run package:api
artifacts:
  files:
    - bin/sam.yaml
  discard-paths: yes