version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test:unit:once
  build:
    commands:
      - npm run build
artifacts:
  files:
    - app/**/*
    - tmp/backend.yaml
