version: 0.1
phases:
  install:
    commands:
      - pip install --upgrade awscli
      - npm install
  pre_build:
    commands:
      - npm run test:unit:once
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run package