version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test:unit:once
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - "aws cloudformation package \
          --template-file tmp/backend.yaml \
          --output-template-file backend.yaml \
          --s3-bucket ${ARTIFACTS_BUCKET} \
          --s3-prefix lambda"
      - aws s3 cp backend.yaml s3://${ARTIFACTS_BUCKET}
# artifacts:
#   files:
#     - backend.yaml