version: 0.1
phases:
  install:
    commands:
      - npm install
      - pip install --upgrade awscli
      - chmod -R +x scripts
  pre_build:
    commands:
      - npm run test:unit:once
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run package
