Parameters:
  BackendStack:
    Type: String
  MinimumPasswordLength:
    Type: Number

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${BackendStack}-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: False
          Required: True
        - Name: name
          AttributeDataType: String
          Mutable: True
          Required: True
      Policies:
        PasswordPolicy:
          MinimumLength: !Ref MinimumPasswordLength
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True

  FrontendClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${BackendStack}-frontend-client
      UserPoolId: !Ref UserPool
      GenerateSecret: False
      ReadAttributes:
        - email
        - name

Outputs:
  UserPoolId:
    Value: !Ref UserPool
