Parameters:
  BackendStack:
    Type: String
  ArtifactsBucket:
    Type: String
  LambdaPackage:
    Type: String
  AuthDomain:
    Type: String
  AuthTokenLifetime:
    Type: Number

Resources:
  Authorizer:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${BackendStack}-Authorizer
      Handler: members.authorize
      Timeout: 10
      Environment:
        Variables:
          AUTH_DOMAIN: !Ref AuthDomain
          AUTH_TOKEN_LIFETIME: !Ref AuthTokenLifetime
      Runtime: nodejs6.10
      Code:
        S3Bucket: !Ref ArtifactsBucket
        S3Key: !Ref LambdaPackage
      Role: !GetAtt LambdaBasicExecutionRole.Arn

  LambdaBasicExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
