version: 2
jobs:
  build:
    docker:
      - image: node:6-alpine
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: pip install yamllint
      - run: npm run lint:templates
      - run: npm run test:unit:once

      - run: bash <(curl -s https://codecov.io/bash)
