version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo

    steps:
      - checkout

      # pip

      - restore_cache:
          keys:
          - pip

      - run: sudo apt-get install libpython-dev
      - run: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run: |
          pip >/dev/null ||
          python <(curl -s https://bootstrap.pypa.io/get-pip.py) --no-wheel --user
      - run pip install --upgrade --user yamllint

      - save_cache:
          paths:
            - ../.local
          key: pip

      # npm

      - run: npm run lint:templates

      - restore_cache:
          keys:
          - npm-{{ checksum "package.json" }}
          - npm

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}

      - run: npm run test:unit:once

      - run: bash <(curl -s https://codecov.io/bash)
