Parameters:
  ArtifactsBucket:
    Type: String
  TemplatesPath:
    Type: String
  LambdaPackage:
    Type: String
  VpcRange:
    Type: String
  EncryptionKeyId:
    Type: String
  SecretsBucket:
    Type: String
  SSHKeyPutRoleArn:
    Type: String
  SSHKeyGetRoleArn:
    Type: String
  DomainZone:
    Type: String
  ApiDomain:
    Type: String
  ApiVersion:
    Type: String
  WebDomain:
    Type: String
  WebBucket:
    Type: String
  WebTTL:
    Type: Number
  WebPriceClass:
    Type: String
  WebLocations:
    Type: String
  WebACL:
    Type: String
  WebSigningKeyPutRoleArn:
    Type: String
  WebSigningKeyGetRoleArn:
    Type: String
  SearchDomain:
    Type: String
  DatasetsBucket:
    Type: String
  ClusterCores:
    Type: Number
  SpotBidPercent:
    Type: Number
  Auth0Domain:
    Type: String
  Auth0ManagementClientID:
    Type: String
  Auth0ManagementClientSecret:
    Type: String
    NoEcho: true
    Default: ''
  Auth0UserTokenLifetime:
    Type: Number
  Auth0PutSecretRoleArn:
    Type: String
  Auth0GetManagementSecretRoleArn:
    Type: String
  Auth0CreateClientRoleArn:
    Type: String

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/api.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        TemplatePath: !Sub ${TemplatesPath}/swagger.yaml
        DomainZone: !Ref DomainZone
        ApiDomain: !Ref ApiDomain
        ApiVersion: !Ref ApiVersion
        WebDomain: !Ref WebDomain

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/vpc.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        VpcRange: !Ref VpcRange

  LogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:PutObject
            Principal:
              Service: !Sub s3.${AWS::Region}.amazonaws.com
            Resource:
              - !Sub arn:aws:s3:::${LogsBucket}/*
            Condition:
              ArnLike:
                'aws:SourceArn': !Sub arn:aws:s3:::${DatasetsBucket}
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId
                's3:x-amz-acl': bucket-owner-full-control
