Parameters:
  ArtifactsBucket:
    Type: String
  TemplatesPath:
    Type: String
  LambdaPackage:
    Type: String
  VpcRange:
    Type: String
  EncryptionKeyId:
    Type: String
  SecretsBucket:
    Type: String
  SSHKeyPutRoleArn:
    Type: String
  SSHKeyGetRoleArn:
    Type: String
  DomainZone:
    Type: String
  ApiDomain:
    Type: String
  ApiVersion:
    Type: String
  WebDomain:
    Type: String
  WebBucket:
    Type: String
  WebTTL:
    Type: Number
  WebPriceClass:
    Type: String
  WebLocations:
    Type: String
  WebACL:
    Type: String
  WebSigningKeyPutRoleArn:
    Type: String
  WebSigningKeyGetRoleArn:
    Type: String
  SearchDomain:
    Type: String
  DataBucket:
    Type: String
  ClusterCores:
    Type: Number
  SpotBidPercent:
    Type: Number
  AuthTokenLifetime:
    Type: Number
  Auth0Domain:
    Type: String
  Auth0ManagementClientID:
    Type: String
  Auth0ManagementClientSecret:
    Type: String
    NoEcho: true
    Default: ''
  Auth0UserTokenLifetime:
    Type: Number
  Auth0PutSecretRoleArn:
    Type: String
  Auth0GetManagementSecretRoleArn:
    Type: String
  Auth0CreateClientRoleArn:
    Type: String

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/api.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        TemplatePath: !Sub ${TemplatesPath}/swagger/${ApiVersion}.yaml
        DomainZone: !Ref DomainZone
        ApiDomain: !Ref ApiDomain
        ApiVersion: !Ref ApiVersion
        WebDomain: !Ref WebDomain

  Web:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/web.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        SecretsBucket: !Ref SecretsBucket
        WebBucket: !Ref WebBucket
        LambdaPackage: !Ref LambdaPackage
        EncryptionKeyId: !Ref EncryptionKeyId
        DomainZone: !Ref DomainZone
        WebDomain: !Ref WebDomain
        WebTTL: !Ref WebTTL
        WebPriceClass: !Ref WebPriceClass
        WebLocations: !Ref WebLocations
        WebACL: !Ref WebACL
        WebSigningKeyPutRoleArn: !Ref WebSigningKeyPutRoleArn
        WebSigningKeyGetRoleArn: !Ref WebSigningKeyGetRoleArn
        ApiId: !GetAtt Api.Outputs.ApiId
        ApiStage: !GetAtt Api.Outputs.ApiStage

  Search:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/search.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        SearchDomain: !Ref SearchDomain

  Projects:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/projects.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LogsBucket: !GetAtt Logs.Outputs.Bucket
        DataBucket: !Ref DataBucket
        LambdaPackage: !Ref LambdaPackage
        WebDomain: !Ref WebDomain
        ApiId: !GetAtt Api.Outputs.ApiId
        ApiStage: !GetAtt Api.Outputs.ApiStage
        SearchUploadDocumentsFunction: !GetAtt Search.Outputs.UploadDocumentsFunction

  Members:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/members.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        AuthDomain: !GetAtt Cognito.Outputs.AuthDomain
        AuthTokenLifetime: !Ref AuthTokenLifetime

  Auth0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/auth0.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        SecretsBucket: !Ref SecretsBucket
        LambdaPackage: !Ref LambdaPackage
        EncryptionKeyId: !Ref EncryptionKeyId
        Auth0Domain: !Ref Auth0Domain
        Auth0ManagementClientID: !Ref Auth0ManagementClientID
        Auth0ManagementClientSecret: !Ref Auth0ManagementClientSecret
        Auth0GetManagementSecretRoleArn: !Ref Auth0GetManagementSecretRoleArn
        Auth0PutSecretRoleArn: !Ref Auth0PutSecretRoleArn
        Auth0CreateClientRoleArn: !Ref Auth0CreateClientRoleArn
        Auth0UserTokenLifetime: !Ref Auth0UserTokenLifetime
        WebDomain: !Ref WebDomain
        ApiDomain: !Ref ApiDomain

  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/cognito.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        WebDomain: !Ref WebDomain
        MinimumPasswordLength: 12

  Data:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/data.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        DataBucket: !Ref DataBucket
        LambdaPackage: !Ref LambdaPackage

  Datasets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/datasets.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        DataBucket: !Ref DataBucket
        LambdaPackage: !Ref LambdaPackage
        WebDomain: !Ref WebDomain
        ApiId: !GetAtt Api.Outputs.ApiId
        ApiStage: !GetAtt Api.Outputs.ApiStage
        SearchDomain: !Ref SearchDomain
        SearchUploadDocumentsFunction: !GetAtt Search.Outputs.UploadDocumentsFunction
        SearchQueryEndpoint: !GetAtt Search.Outputs.QueryEndpoint
        SearchStackSuffix: !GetAtt Search.Outputs.StackSuffix
        TagDataStateMachine: !GetAtt Data.Outputs.TagDataStateMachine

  Pipelines:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/pipelines.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        WebDomain: !Ref WebDomain
        ApiId: !GetAtt Api.Outputs.ApiId
        ApiStage: !GetAtt Api.Outputs.ApiStage
        SearchUploadDocumentsFunction: !GetAtt Search.Outputs.UploadDocumentsFunction

  Analyses:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/analyses.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        DataBucket: !Ref DataBucket
        LambdaPackage: !Ref LambdaPackage
        WebDomain: !Ref WebDomain
        ApiId: !GetAtt Api.Outputs.ApiId
        ApiStage: !GetAtt Api.Outputs.ApiStage
        SearchDomain: !Ref SearchDomain
        SearchUploadDocumentsFunction: !GetAtt Search.Outputs.UploadDocumentsFunction
        SearchQueryEndpoint: !GetAtt Search.Outputs.QueryEndpoint
        SearchStackSuffix: !GetAtt Search.Outputs.StackSuffix
        PipelinesTable: !GetAtt Pipelines.Outputs.Table
        JobQueue: !GetAtt Batch.Outputs.JobQueue

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/vpc.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        VpcRange: !Ref VpcRange

  Instances:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/instances.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        SecretsBucket: !Ref SecretsBucket
        LambdaPackage: !Ref LambdaPackage
        SubnetIds: !GetAtt VPC.Outputs.SubnetIds
        SecurityGroup: !GetAtt VPC.Outputs.DefaultSecurityGroup
        EncryptionKeyId: !Ref EncryptionKeyId
        SSHKeyGetRoleArn: !Ref SSHKeyGetRoleArn
        SSHKeyPutRoleArn: !Ref SSHKeyPutRoleArn

  Batch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/batch.yaml
      Parameters:
        BackendStack: !Ref AWS::StackName
        ArtifactsBucket: !Ref ArtifactsBucket
        LambdaPackage: !Ref LambdaPackage
        SubnetIds: !GetAtt VPC.Outputs.SubnetIds
        SecurityGroup: !GetAtt VPC.Outputs.DefaultSecurityGroup
        ClusterCores: !Ref ClusterCores
        SpotBidPercent: !Ref SpotBidPercent
        SSHKeyName: !GetAtt Instances.Outputs.SSHKeyName

  Logs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPath}/logs.yaml
      Parameters:
        DataBucket: !Ref DataBucket
