export const envNames = {
  encryptionKeyId: 'ENCRYPTION_KEY_ID',
  stateMachine: 'STATE_MACHINE',
  routeTable: 'ROUTE_TABLE',
  sshKeyName: 'SSH_KEY_NAME',
  sshKeyS3Bucket: 'SSH_KEY_S3_BUCKET',
  sshKeyS3Path: 'SSH_KEY_S3_PATH',
  sshUser: 'SSH_USER',
  mountPath: 'MOUNT_PATH',
  apiDomain: 'API_DOMAIN',
  webDomain: 'WEB_DOMAIN',
  webDistributionId: 'WEB_DISTRIBUTION_ID',
  webSigningKeyBucket: 'WEB_SIGNING_KEY_BUCKET',
  webSigningKeyPath: 'WEB_SIGNING_KEY_PATH',
  datasetsTable: 'DATASETS_TABLE',
  auth0Domain: 'AUTH0_DOMAIN',
  auth0ClientId: 'AUTH0_CLIENT_ID',
  auth0SecretBucket: 'AUTH0_SECRET_BUCKET',
  auth0SecretPath: 'AUTH0_SECRET_PATH',
};
