export const envNames = {
  encryptionKeyId: 'ENCRYPTION_KEY_ID',
  stateMachine: 'STATE_MACHINE',
  routeTable: 'ROUTE_TABLE',
  apiDomain: 'API_DOMAIN',
  webDomain: 'WEB_DOMAIN',
  webDistributionId: 'WEB_DISTRIBUTION_ID',
  webSigningKeyBucket: 'WEB_SIGNING_KEY_BUCKET',
  webSigningKeyPath: 'WEB_SIGNING_KEY_PATH',
  datasetsTable: 'DATASETS_TABLE',
  projectsTable: 'PROJECTS_TABLE',
  pipelinesTable: 'PIPELINES_TABLE',
  searchStackSuffix: 'SEARCH_STACK_SUFFIX',
  searchDocEndpoint: 'SEARCH_DOC_ENDPOINT',
  searchQueryEndpoint: 'SEARCH_QUERY_ENDPOINT',
  auth0Domain: 'AUTH0_DOMAIN',
  auth0ClientId: 'AUTH0_CLIENT_ID',
  auth0SecretBucket: 'AUTH0_SECRET_BUCKET',
  auth0SecretPath: 'AUTH0_SECRET_PATH',
  datasetsBucket: 'DATASETS_BUCKET',
  logsBucket: 'LOGS_BUCKET',
  datasetsRole: 'DATASETS_ROLE',
};
