export const envNames = {
  accountId: 'ACCOUNT_ID',
  stackName: 'STACK_NAME',
  encryptionKeyId: 'ENCRYPTION_KEY_ID',
  stateMachine: 'STATE_MACHINE',
  routeTable: 'ROUTE_TABLE',
  apiDomain: 'API_DOMAIN',
  webDomain: 'WEB_DOMAIN',
  webDistributionId: 'WEB_DISTRIBUTION_ID',
  webSigningKeyBucket: 'WEB_SIGNING_KEY_BUCKET',
  webSigningKeyPath: 'WEB_SIGNING_KEY_PATH',
  datasetsTable: 'DATASETS_TABLE',
  projectsTable: 'PROJECTS_TABLE',
  pipelinesTable: 'PIPELINES_TABLE',
  analysesTable: 'ANALYSES_TABLE',
  searchStackSuffix: 'SEARCH_STACK_SUFFIX',
  searchDocEndpoint: 'SEARCH_DOC_ENDPOINT',
  searchQueryEndpoint: 'SEARCH_QUERY_ENDPOINT',
  authDomain: 'AUTH_DOMAIN',
  authTokenLifetime: 'AUTH_TOKEN_LIFETIME',
  auth0Domain: 'AUTH0_DOMAIN',
  auth0ClientId: 'AUTH0_CLIENT_ID',
  auth0SecretBucket: 'AUTH0_SECRET_BUCKET',
  auth0SecretPath: 'AUTH0_SECRET_PATH',
  dataBucket: 'DATA_BUCKET',
  logsBucket: 'LOGS_BUCKET',
  roleArn: 'ROLE_ARN',
};
